# Generated by Django 4.2.14 on 2024-07-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='lastt_name',
            new_name='last_name',
        ),
    ]
